import type { Metadata } from "next";
import "./globals.css";
import NavHeader from "@/components/navigation";
import Footer from "@/components/footer";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <NavHeader />
      <body className="antialiased">{children}</body>
      <Footer />
    </html>
  );
}
